[package]
name = "stele"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
anyhow = "1.0"
clap = { version = "4.0.27", features = ["derive"] }
git2 = "0.15"
lazy_static = "1.4.0"
regex = "1"
serde = "1.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "git_benchmark"
harness = false
